# Generated by Django 4.2.19 on 2025-03-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='status Name')),
            ],
            options={
                'verbose_name': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='Invoice Number')),
                ('oay_amount', models.IntegerField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.invoicestatus', verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'Invoice',
            },
        ),
    ]
