# Generated by Django 4.2.20 on 2025-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='oay_amount',
            new_name='pay_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
    ]
