# Generated by Django 4.2.20 on 2025-03-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_rename_oay_amount_invoice_pay_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_name',
        ),
    ]
