# Generated by Django 4.2.20 on 2025-03-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0006_invoice_invoice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_name',
        ),
    ]
