# Generated by Django 4.2.20 on 2025-03-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_remove_invoice_invoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
    ]
