# Generated by Django 4.2.20 on 2025-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0002_delete_invoiceextended'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_name', models.CharField(max_length=64, null=True, verbose_name='Name')),
            ],
        ),
    ]
