# Generated by Django 4.2.20 on 2025-03-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceExtended',
        ),
    ]
